services:
  - type: web
    name: weather-forecast-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python weather_forecast_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
